SOURCE = ft_read_dict.c ft_read_param.c main.c ft_error.c ft_string.c

NAME = rush-02

CFLAGS = -Wall -Wextra -Werror

all : ${NAME}

${NAME} : 
	cc ${CFLAGS} ${SOURCE} -o ${NAME}

fclean :
	rm -f ${NAME}
